export const API_KEY = process.env.NEXT_PUBLIC_FIREBASE_API_KEY
export const DATABASE_URL = process.env.NEXT_PUBLIC_FIREBASE_DATABASE_URL
export const PROJECT_ID = process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID
