export const API_KEY = process.env.NEXT_PUBLIC_FIREBASE_API_KEY
export const DATABASE_URL = process.env.NEXT_PUBLIC_FIREBASE_DATABASE_URL
export const PROJECT_ID = process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID
export const SENDGRID_KEY = process.env.NEXT_PUBLIC_SENDGRID_API_KEY
export const MAIL_ADDRESS = process.env.NEXT_PUBLIC_MAIL_ADDRESS
export const MAIL_PASSWORD = process.env.NEXT_PUBLIC_MAIL_PASSWORD
